export const OVERLAY_CSS = `
:host { all: initial; color-scheme: light dark; }
*, *::before, *::after { box-sizing: border-box; }
button, input, textarea, select { font: inherit; }
.a3s-announcer { position:fixed; width:1px; height:1px; padding:0; margin:-1px; overflow:hidden; clip:rect(0 0 0 0); clip-path:inset(50%); white-space:nowrap; border:0; }
.a3s-root { position: fixed; inset: 0; z-index: 2147483646; pointer-events: none; font: 13px/1.45 ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: #f5f5f4; }
.a3s-launch { pointer-events: auto; position: fixed; right: 20px; bottom: 20px; border: 1px solid #57534e; border-radius: 999px; padding: 10px 14px; background: #1c1917; color: #fafaf9; box-shadow: 0 8px 30px rgba(0,0,0,.28); cursor: pointer; font-weight: 700; }
.a3s-launch.is-active { outline: 3px solid rgba(249,115,22,.35); border-color: #fb923c; }
.a3s-panel { pointer-events: auto; position: fixed; right: 20px; bottom: 70px; width: min(390px, calc(100vw - 32px)); max-height: min(720px, calc(100vh - 100px)); display: flex; flex-direction: column; overflow: hidden; background: #1c1917; border: 1px solid #44403c; border-radius: 14px; box-shadow: 0 20px 65px rgba(0,0,0,.42); }
header { display:flex; align-items:flex-start; justify-content:space-between; padding:15px 16px 12px; border-bottom:1px solid #44403c; } header div { display:flex; flex-direction:column; gap:2px; } header strong { font-size:15px; } small { color:#a8a29e; } header button { border:0; background:none; color:#d6d3d1; cursor:pointer; font-size:20px; line-height:1; }
.a3s-tools { display:flex; flex-wrap:wrap; gap:6px; padding:10px 12px; border-bottom:1px solid #292524; } .a3s-tools button { flex:1 1 58px; } button { border:1px solid #57534e; border-radius:7px; padding:7px 9px; background:#292524; color:#f5f5f4; cursor:pointer; } button:hover, button.selected { border-color:#fb923c; background:#431407; } button:disabled { opacity:.45; cursor:not-allowed; } button.danger { color:#fecaca; }
button:focus-visible, input:focus-visible, textarea:focus-visible, select:focus-visible, .a3s-panel:focus-visible { outline:3px solid currentColor; outline-offset:2px; }
.a3s-hint { margin:0; padding:8px 12px; background:#431407; color:#fed7aa; }
.a3s-highlight { position:fixed; pointer-events:none; border:2px solid #f97316; background:rgba(249,115,22,.12); box-shadow:0 0 0 1px rgba(255,255,255,.75) inset; }
.a3s-wireframe { position:fixed; inset:16px; pointer-events:none; border:1px solid rgba(249,115,22,.55); background:linear-gradient(90deg, rgba(249,115,22,.08) 1px, transparent 1px),linear-gradient(rgba(249,115,22,.08) 1px, transparent 1px); background-size:24px 24px; }
.a3s-layout-target-preview { position:fixed; pointer-events:none; border:2px dashed #38bdf8; background:rgba(14,165,233,.1); box-shadow:0 0 0 1px rgba(255,255,255,.75) inset; }
.a3s-markers { position:fixed; inset:0; pointer-events:none; } .a3s-marker { position:fixed; border:2px solid #f97316; border-radius:4px; padding:0; background:rgba(249,115,22,.08); } .a3s-marker-action { pointer-events:auto; position:absolute; inset:-2px auto auto -2px; display:grid; place-items:center; width:28px; height:28px; padding:5px; border-color:#fed7aa; border-radius:6px; background:#431407; color:#fff7ed; cursor:pointer; } .a3s-marker-action svg { width:14px; height:14px; fill:none; stroke:currentColor; stroke-width:1.5; stroke-linecap:round; stroke-linejoin:round; } .a3s-marker.status-review_ready, .a3s-marker.status-resolved { border-color:#22c55e; background:rgba(34,197,94,.08); } .a3s-marker.status-failed, .a3s-marker.status-verification_failed { border-color:#ef4444; background:rgba(239,68,68,.08); }
.a3s-drawing { position:fixed; inset:0; width:100vw; height:100vh; pointer-events:none; overflow:visible; } .a3s-drawing path { fill:none; stroke:#f97316; stroke-width:3; stroke-linecap:round; stroke-linejoin:round; filter:drop-shadow(0 0 1px #fff); }
.a3s-layout { display:flex; flex-direction:column; gap:9px; padding:12px; border-bottom:1px solid #44403c; background:#292524; } .a3s-layout > p { margin:0; color:#a8a29e; } .a3s-layout label { display:flex; flex-direction:column; gap:4px; font-weight:600; } .a3s-layout label span { color:#a8a29e; font-weight:400; } .a3s-layout input[type="text"], .a3s-layout input[type="number"] { width:100%; color:#f5f5f4; background:#0c0a09; border:1px solid #57534e; border-radius:7px; padding:8px; } .a3s-layout-fields { display:grid; grid-template-columns:1fr 1fr; gap:8px; } .a3s-layout-source { display:flex; flex-direction:column; gap:6px; padding-top:3px; border-top:1px solid #44403c; } .a3s-layout-source > span { color:#a8a29e; } .a3s-layout-source strong { overflow-wrap:anywhere; }
.a3s-editor { display:flex; flex-direction:column; gap:9px; padding:12px; border-bottom:1px solid #44403c; background:#292524; } .a3s-editor label { display:flex; flex-direction:column; gap:4px; font-weight:600; } .a3s-editor label span { color:#78716c; font-weight:400; } textarea, select { width:100%; color:#f5f5f4; background:#0c0a09; border:1px solid #57534e; border-radius:7px; padding:8px; } textarea { resize:vertical; min-height:58px; } .a3s-fields { display:grid; grid-template-columns:1fr 1fr; gap:8px; } .a3s-actions { display:flex; justify-content:flex-end; gap:6px; flex-wrap:wrap; } button.quiet { border-color:transparent; background:transparent; color:#d6d3d1; }
.a3s-conflicts { display:flex; flex-direction:column; gap:6px; margin:0; padding:8px; border:1px solid #57534e; border-radius:7px; } .a3s-conflicts legend { padding:0 4px; font-weight:600; } .a3s-conflicts legend span { color:#78716c; font-weight:400; } .a3s-conflicts label { flex-direction:row; align-items:flex-start; font-weight:400; } .a3s-conflicts input { margin-top:3px; }
.a3s-list { overflow:auto; padding:8px 12px; display:flex; flex-direction:column; gap:8px; } .a3s-item { display:flex; flex-direction:column; gap:8px; padding:10px; border:1px solid #44403c; border-radius:9px; background:#292524; } .a3s-item.is-hidden { opacity:.62; } .a3s-item label { display:flex; gap:9px; align-items:flex-start; } .a3s-item label span, .a3s-item.submitted { display:flex; flex-direction:column; gap:3px; } .a3s-item strong { overflow-wrap:anywhere; } .a3s-item div { display:flex; flex-wrap:wrap; gap:6px; } .a3s-status { align-self:flex-start; border-radius:999px; padding:2px 7px; color:#fed7aa; background:#431407; text-transform:capitalize; font-size:11px; } .status-resolved, .status-review_ready { color:#bbf7d0; background:#052e16; } .status-failed, .status-verification_failed { color:#fecaca; background:#450a0a; } .a3s-empty { color:#a8a29e; text-align:center; padding:20px 10px; }
.a3s-thread { display:flex; flex-direction:column; gap:6px; margin:5px 0 0; padding:8px; list-style:none; border-top:1px solid #44403c; } .a3s-thread li { display:grid; grid-template-columns:auto 1fr; gap:8px; align-items:start; } .a3s-thread span { color:#fdba74; font-size:11px; text-transform:capitalize; } .a3s-thread p { margin:0; white-space:pre-wrap; overflow-wrap:anywhere; }
.a3s-human-actions { display:flex; flex-wrap:wrap; gap:6px; align-items:flex-end; } .a3s-reply-label { display:flex; flex:1 1 100%; flex-direction:column; gap:4px; font-weight:600; } .a3s-reply-label textarea { min-height:52px; }
footer { display:flex; justify-content:flex-end; gap:7px; padding:11px 12px; border-top:1px solid #44403c; background:#0c0a09; }
@media (prefers-color-scheme: light) { .a3s-panel { background:#fafaf9; border-color:#d6d3d1; color:#1c1917; } header, .a3s-tools, .a3s-layout, .a3s-editor, footer { border-color:#e7e5e4; } .a3s-layout, .a3s-editor, .a3s-item { background:#f5f5f4; border-color:#d6d3d1; } .a3s-layout input[type="text"], .a3s-layout input[type="number"], textarea, select { background:#fff; color:#1c1917; border-color:#a8a29e; } button { background:#e7e5e4; color:#1c1917; border-color:#a8a29e; } button.quiet, header button { color:#57534e; } }
.a3s-root[data-theme="light"] .a3s-panel { background:#fafaf9; border-color:#d6d3d1; color:#1c1917; } .a3s-root[data-theme="light"] header, .a3s-root[data-theme="light"] .a3s-tools, .a3s-root[data-theme="light"] .a3s-layout, .a3s-root[data-theme="light"] .a3s-editor, .a3s-root[data-theme="light"] footer { border-color:#e7e5e4; } .a3s-root[data-theme="light"] .a3s-layout, .a3s-root[data-theme="light"] .a3s-editor, .a3s-root[data-theme="light"] .a3s-item { background:#f5f5f4; border-color:#d6d3d1; } .a3s-root[data-theme="light"] .a3s-layout input[type="text"], .a3s-root[data-theme="light"] .a3s-layout input[type="number"], .a3s-root[data-theme="light"] textarea, .a3s-root[data-theme="light"] select { background:#fff; color:#1c1917; border-color:#a8a29e; } .a3s-root[data-theme="light"] button { background:#e7e5e4; color:#1c1917; border-color:#a8a29e; }
@media (max-width: 600px) { .a3s-panel { left:8px; right:8px; bottom:64px; width:auto; max-height:calc(100vh - 76px); } .a3s-launch { right:12px; bottom:12px; } }
`;
