import type { ExperienceCopy, Locale, LocalizedCopy } from './home-copy-types';

export type { ExperienceCopy, Locale } from './home-copy-types';

export const homeCopy: Record<Locale, LocalizedCopy> = {
  zh: {
    heroTitle: ['让 Agent 基于真实页面行动', '把每次修改证明给你看'],
    heroBody:
      '选中界面问题，带着当前修订、组件与源码线索交给 Agent，再用更新后的页面验证结果。A3S Test 把这条反馈闭环变成可执行、可复查的测试。',
    startExperience: '在本页试用 Test Kit',
    readDocs: '运行第一个测试',
    proofItems: [
      {
        title: '读取当前渲染',
        body: '语义、状态、几何与页面修订来自正在运行的浏览器。',
      },
      {
        title: '绑定负责源码',
        body: '组件、定位器、区域与源码候选跟随同一个问题。',
      },
      {
        title: '只认新证据',
        body: '更新后的页面重新验证结果，再把稳定路径写成 ACL。',
      },
    ],
    workflow: {
      title: '把需求、界面与证据连成一条可回放路径',
      body: '完整流程从 PRD、设计参考和运行页面同时开始。编码 Agent 负责理解与规划，A3S Test 约束每次浏览器行动、保存证据，并把已经证明的路径固化成确定性回归。',
      stageAria: 'A3S Test 完整工作流导览',
      stageLabel: 'checkout-ui · 工作流导览',
      pause: '暂停工作流导览',
      resume: '继续工作流导览',
      manual: '手动选择阶段',
      boundaryTitle: '职责边界',
      boundaryBody:
        '编码 Agent 做理解、场景规划与修复。A3S Test 不再调用第二个 LLM 做决策，只校验并执行一个类型化动作；上方公开演示仍只使用当前标签页内存。',
      steps: [
        {
          label: '输入契约',
          status: 'INPUT CONTRACT',
          title: '把 PRD、设计参考与运行页面放进同一上下文',
          body: '需求说明定义目标，设计参考约束视觉，浏览器提供当前事实。三类输入各自有边界，不互相冒充。',
          sourceTitle: '三类输入',
          sources: [
            {
              label: 'checkout-requirements.md',
              detail: '业务规则 · 可观察成功条件',
            },
            {
              label: 'design-reference.png',
              detail: '视觉目标 · 布局意图',
            },
            {
              label: 'localhost:3000/checkout',
              detail: '运行界面 · 当前页面修订',
            },
          ],
          processTitle: '建立任务契约',
          processLead: '先明确页面能够证明什么',
          processRows: [
            { label: '目标', value: '提交订单后进入确认状态' },
            { label: '成功条件', value: '“订单已确认”标题可见' },
            { label: '范围', value: '/checkout · 同源页面' },
            { label: '权限', value: '读取证据，不自动授权改源码' },
          ],
          outputTitle: '任务契约',
          outputLines: [
            'goal        observable',
            'reference   bounded',
            'target      running page',
            'authority   unchanged',
          ],
        },
        {
          label: '理解 UI',
          status: 'UI UNDERSTANDING',
          title: '读取语义、状态与几何，再对照设计意图',
          body: 'Page Context 与 UI Understanding 从真实渲染中提取可访问语义、交互状态、布局关系与源码候选，设计图只作为有界参考。',
          sourceTitle: '当前页面事实',
          sources: [
            { label: 'render revision 18', detail: 'DOM · 可访问树 · 样式' },
            { label: 'Page Context', detail: '组件 · 定位器 · 源码候选' },
            { label: 'design reference', detail: '区域对照 · 预期层级' },
          ],
          processTitle: '界面模型',
          processLead: '当前修订上的可执行 UI 语义',
          processRows: [
            { label: '语义', value: 'button · “提交订单”' },
            { label: '状态', value: 'default · hover · disabled' },
            { label: '几何', value: 'viewport box · layout graph' },
            { label: '归属', value: 'CheckoutForm · source candidate' },
          ],
          outputTitle: '可验证目标',
          outputLines: [
            'role        button',
            'name        “提交订单”',
            'locator     role(button, name)',
            'criterion   confirmation visible',
          ],
        },
        {
          label: '规划场景',
          status: 'SCENARIO PLAN',
          title: '由编码 Agent 把成功条件拆成可执行场景',
          body: 'Agent 结合任务契约、最新观察与驱动能力规划正常路径和失败分支。A3S Test 提供执行约束，不替 Agent 做模型决策。',
          sourceTitle: '规划依据',
          sources: [
            { label: 'goal + success', detail: '目标与成功条件' },
            { label: 'UI model', detail: '可操作目标与页面状态' },
            { label: 'driver schema', detail: '当前 surface 可证明的动作' },
          ],
          processTitle: '场景规划',
          processLead: '从可观察结果反推最小路径',
          processRows: [
            { label: '规划者', value: '拥有上下文的编码 Agent' },
            { label: '主路径', value: '提交 → 确认状态' },
            { label: '失败分支', value: '校验提示保持可见' },
            { label: '决策来源', value: '最新观察，不调用第二个 LLM' },
          ],
          outputTitle: '场景草案',
          outputLines: [
            'scenario    submit-order',
            'precondition checkout ready',
            'path        submit → confirmation',
            'failure     validation stays visible',
          ],
        },
        {
          label: '探索执行',
          status: 'AGENT SESSION',
          title: '在持久会话中每次只执行一个类型化动作',
          body: '会话保留浏览器状态，但引用只绑定最新 observation。每个动作之后重新观察，旧引用和越权导航都会失败关闭。',
          sourceTitle: '会话输入',
          sources: [
            { label: 'session checkout', detail: '目标 · 成功条件 · 同源策略' },
            { label: 'observation_id 1', detail: '最新语义页面状态' },
            { label: '@e1 [button]', detail: '提交订单 · 观察绑定引用' },
          ],
          processTitle: '观察与行动闭环',
          processLead: 'Start → Observe → Decide → Act → Observe',
          processRows: [
            { label: 'Start', value: '开启拥有明确目标的会话' },
            { label: 'Observe', value: '取得新 observation 与 refs' },
            { label: 'Decide', value: '编码 Agent 选择下一步' },
            { label: 'Act', value: '执行一次，再立即观察' },
          ],
          outputTitle: '类型化命令',
          outputLines: [
            'agent start /checkout --session checkout',
            'agent observe --session checkout --json',
            'agent click @e1 --observation 1',
            'agent observe --session checkout --json',
          ],
        },
        {
          label: '固化 ACL',
          status: 'DETERMINISTIC ACL',
          title: '把已证明的稳定路径收敛成确定性回归',
          body: '探索阶段的临时引用不会直接进入套件。ACL 只保留稳定定位、明确等待、断言与必要证据，然后先检查再运行。',
          sourceTitle: '已证明路径',
          sources: [
            { label: 'events.jsonl', detail: '实际动作与观察顺序' },
            { label: 'stable locator', detail: 'role · name · CSS contract' },
            { label: 'observable assertion', detail: '可见确认状态' },
          ],
          processTitle: '回归收敛',
          processLead: '只接纳能够在新浏览器中重放的步骤',
          processRows: [
            { label: '动作', value: '稳定语义定位，不保存临时 ref' },
            { label: '等待', value: '有界稳定窗口' },
            { label: '断言', value: '页面可直接观察的结果' },
            { label: '清理', value: '关闭会话拥有的 surface' },
          ],
          outputTitle: 'checkout.acl',
          outputLines: [
            'click       role(button, “提交订单”)',
            'expect      text “订单已确认”',
            'a3s-test check tests/e2e/checkout.acl',
            'a3s-test run tests/e2e/checkout.acl',
          ],
        },
        {
          label: '证据闭环',
          status: 'EVIDENCE → CI',
          title: '归因失败、完成修复，再用同一契约验证与回放',
          body: '运行结果按产品、规格或基础设施问题归因。编码 Agent 修复后，A3S Test 在新页面上复验，并让同一 ACL 进入 CI。',
          sourceTitle: '运行证据',
          sources: [
            { label: 'screenshot', detail: '最终视觉状态' },
            { label: 'a11y + runtime', detail: '语义 · console · page errors' },
            { label: 'report + event log', detail: '判定 · 动作 · 清理结果' },
          ],
          processTitle: '诊断与回放',
          processLead: '证据决定下一步，不用猜测替代结果',
          processRows: [
            {
              label: '归因',
              value: 'product / specification / infrastructure',
            },
            { label: '修复', value: '由获授权的编码 Agent 完成' },
            { label: '验证', value: '更新后的页面重新观察与断言' },
            { label: '回放', value: '同一 ACL 在本地与 CI 执行' },
          ],
          outputTitle: '验证记录',
          outputLines: [
            'classification product',
            'fix_owner     coding-agent',
            'verify        fresh-browser + CI replay',
            'cleanup       owned surface closed',
          ],
        },
      ],
      evidenceTitle: '每次运行保留最小、可审查的证据',
      evidenceItems: [
        { label: 'SCREENSHOT', detail: '最终视觉状态' },
        { label: 'ACCESSIBILITY', detail: '语义与可操作性' },
        { label: 'CONSOLE', detail: '浏览器日志' },
        { label: 'PAGE ERRORS', detail: '未捕获运行时错误' },
        { label: 'HAR · TRACE · VIDEO', detail: '只在需要时采集' },
      ],
      evidenceNote:
        '失败按 product / specification / infrastructure 分类；HAR、trace 与 video 按需开启。每个会话都以 finish 或 abort 结束，并清理自己拥有的资源。',
    },
    installTitle: '一个命令安装运行核心',
    installBody:
      'CLI 与 Agent Skill 用于会话和 ACL。需要在页面中点选、框选、截图或画草图时，再接入 Test Kit。',
    testkitInstallLink: '按需接入 Web Test Kit',
    installTabs: '选择安装平台',
    installPackage: 'CLI + Agent Skill',
    installNote: '安装器校验发布归档的 SHA-256，并保持 CLI 与 Skill 版本一致。',
    installCandidateNote:
      '当前文档已进入下一版本准备阶段。此命令仍固定安装已发布的稳定版。',
    copy: '复制命令',
    copied: '命令已复制',
    copyError: '复制失败，请手动选择命令',
    benchmark: {
      title: '同一组任务，先看完成率，再看安全与代价',
      body: '这次对比隔离了执行层：双方使用同一个确定性求解器和相同的浏览器底层，MiniWoB 官方 reward 是唯一成功判定。',
      tableCaption: 'A3S Test 与直接 agent-browser 的 UI 执行层对比',
      dimension: '对比维度',
      candidate: 'A3S Test 1.0.0',
      baseline: '直接 agent-browser 0.26.0',
      metrics: {
        success: '任务成功',
        staleReference: '旧引用防护',
        evidence: '内置运行证据',
        latency: '共同成功中位执行时间',
      },
      labels: {
        mainRuns: '次主运行',
        staleRejected: '旧引用被拒绝',
        pageMutations: '次页面修改',
        artifactRuns: '次运行生成内置证据文件',
        versusDirect: '相对直接客户端',
        hostBaseline: '本机基线',
        lockedProtocol: 'MiniWoB++ 锁定协议',
        tasks: '项任务',
        repetitions: '次重复',
      },
      limitation:
        '这是单机开发证据，不比较模型推理，也不代表通用性能。拖拽与滚轮探针在双方均超时，未计入主成功率。',
      reportLink: '查看完整协议、原始数据与复现步骤',
    },
    packetTitle: '给 Agent 的不只是一句“这里有问题”',
    packetBody:
      'Test Kit 把人工意图与浏览器已经计算出的上下文组成一个有界交接包。Agent 能知道目标是什么、由谁负责、证据来自哪一版页面。',
    packetLabel: '交接包示例',
    packetLines: [
      'protocol    a3s.test.repair/1',
      'page        /checkout · revision 18',
      'selection   button “提交订单”',
      'source      TestKitExperience.tsx',
      'intent      提高文字对比度',
      'context     role · locator · viewport geometry',
      'authority   human submitted',
    ],
    packetTrust:
      '页面内容始终按不可信证据处理。点选、截图或保存草稿都不会自动授权修改源码。',
    packetLink: '查看 Page Context、权限与失败关闭规则',
    quickStartTitle: '三步跑通第一个真实页面',
    quickStartBody:
      '先让应用照常运行，再为一次明确目标开启会话。每次只依据最新观察执行一个类型化动作。',
    quickStartSteps: [
      {
        title: '运行你的页面',
        body: '使用项目原来的开发命令，不需要为 A3S Test 改构建流程。',
        command: 'npm run dev',
      },
      {
        title: '开启一个有成功条件的会话',
        body: '目标和成功条件必须能从页面直接观察。',
        command:
          'a3s-test agent start http://127.0.0.1:3000 \\\n  --session ui \\\n  --goal "复现提交失败" \\\n  --success "确认页标题可见"',
      },
      {
        title: '先观察，再行动',
        body: '读取最新引用，完成验证后再把稳定路径收敛成 ACL。',
        command: 'a3s-test agent observe --session ui --interactive --json',
      },
    ],
    quickStartLink: '打开完整快速开始',
    faqTitle: '先回答会影响你决定的问题',
    faqBody: '边界说清楚，比把所有能力一次铺开更重要。',
    faqItems: [
      {
        question: '普通 Web 测试必须接入 Test Kit 吗？',
        answer:
          '不需要。CLI 可以直接驱动浏览器。只有当组件归属、源码候选、页面几何、截图草图或人工标记确实能帮助任务时，才接入 Test Kit。',
      },
      {
        question: '页面截图会请求整个屏幕的权限吗？',
        answer:
          '不会。Test Kit 截取的是当前浏览器页面内容，并在页面内框选区域；它不调用整屏共享或系统级屏幕录制。',
      },
      {
        question: '点选元素后会直接让 Agent 修改源码吗？',
        answer:
          '不会。点选和草稿只生成证据。只有用户明确提交的问题才进入修复队列，工作区修改仍属于单独授权的编码 Agent。',
      },
      {
        question: '页面滚动或更新后，旧标记会不会漂移？',
        answer:
          '标记会根据当前滚动位置重新计算。页面修订变化后，无法证明仍然有效的旧引用和几何会失效，不会悄悄指向另一个元素。',
      },
      {
        question: 'Agent 会话和 ACL 为什么同时存在？',
        answer:
          '会话用于路径未知的探索，每次根据最新观察选择动作。ACL 只保存已经证明过的明确动作、等待、断言与证据，用于本地和 CI 重复。',
      },
    ],
    ctaTitle: '从一个真实页面开始',
    ctaBody:
      '先用 CLI 跑通一个带可观察成功条件的会话。需要更多页面上下文时再接入 Test Kit。',
    quickStart: '运行第一个测试',
    testkitGuide: '接入 Test Kit',
    footer: '依据当前页面行动，把证明过的路径变成回归。',
    experience: {
      stageAria: 'A3S Test Kit 实时体验',
      boundaryName: '订单确认体验',
      sample: '交互演示',
      shop: 'A3S Shop',
      checkoutTitle: '确认订单',
      checkoutProgress: ['购物车', '确认订单', '支付', '完成'],
      customerTitle: '收货信息',
      customerName: '张三 · 138 0000 0000',
      customerAddress: '北京市海淀区中关村大街 1 号 A3S 大厦 1001 室',
      productsTitle: '商品清单',
      productName: 'A3S 自动化测试套件',
      productVariant: '团队版 · 年度许可',
      quantity: '数量 1',
      subtotal: '¥1,298.00',
      totalDue: '¥1,248.00',
      summaryTitle: '订单金额',
      productTotal: '商品总额',
      delivery: '运费',
      deliveryValue: '¥0.00',
      discount: '优惠',
      discountValue: '−¥50.00',
      payable: '实付金额',
      paymentTitle: '支付方式',
      paymentMethod: '企业测试账户',
      submit: '提交订单',
      submitted: '演示订单已提交，页面上下文已刷新。',
      contextTitle: '页面上下文',
      refresh: '刷新',
      connecting: '正在读取真实页面上下文…',
      contextUnavailable: '未读到页面上下文，请刷新重试。',
      notAvailable: '暂无',
      selected: '当前目标',
      revision: '页面修订',
      role: '角色',
      name: '名称',
      geometry: '视口几何',
      locator: '首选定位器',
      source: '组件来源',
      reviewTitle: '标记页面问题',
      reviewBody: '点选元素并写清期望结果。多个相关问题可以一起整理后保存。',
      openReview: '开始标记',
      reviewStarted: '标记工具已打开',
      live: '实时',
      localOnly:
        '此演示只把问题保存在当前标签页，不连接修复 Agent，也不会修改源码。',
      evidenceTitle: '本页问题',
      evidenceWaiting: '尚未保存',
      evidenceReady: '已保存到本页',
      receiptId: '记录 ID',
      receiptStatus: '保存位置',
      receiptFindings: '问题数量',
      receiptMemory: '当前标签页',
      receiptIdle: '尚未保存',
      findingUnit: '个问题',
      findingsUnit: '个问题',
      noFinding: '尚未保存问题',
      renderedStatus: '渲染完成',
      contextStatus: '上下文已绑定',
      evidenceStatus: '本地保存',
      motionSteps: ['读取页面', '绑定目标', '说明问题', '组成批次', '保存本页'],
      scanSummary: 'DOM · 语义 · 坐标',
      targetMarker: '目标',
      motionFinding: '已绑定“提交订单”',
      motionRequest: '提高按钮文字对比度，保持尺寸与位置不变。',
      motionPacket: '1 个问题 · 已绑定当前修订',
      motionContext: '实时上下文',
      motionContextValue: 'button · 提交订单',
      motionAdd: '加入批次',
      motionSend: '保存到本页',
      motionReady: '问题已保存到当前标签页',
      motionPause: '暂停自动演示',
      motionResume: '继续自动演示',
    },
  },
  en: {
    heroTitle: [
      'Ground the agent in the real page.',
      'Keep proof of every change.',
    ],
    heroBody:
      'Select an interface problem, carry the current revision, component, and source hints to the agent, then verify the result against the changed page. A3S Test turns that feedback loop into an executable, inspectable test.',
    startExperience: 'Try Test Kit on this page',
    readDocs: 'Run your first test',
    proofItems: [
      {
        title: 'Read the current render',
        body: 'Semantics, state, geometry, and page revision come from the running browser.',
      },
      {
        title: 'Bind the owning source',
        body: 'Components, locators, regions, and source candidates travel with one finding.',
      },
      {
        title: 'Accept only fresh proof',
        body: 'Verify against the changed page, then preserve the stable path as ACL.',
      },
    ],
    workflow: {
      title: 'Connect intent, interface, and evidence into one replayable path',
      body: 'The complete flow starts with the PRD, design reference, and running page together. The coding agent understands and plans; A3S Test constrains each browser action, retains evidence, and turns only proven paths into deterministic regressions.',
      stageAria: 'Complete A3S Test workflow walkthrough',
      stageLabel: 'checkout-ui · workflow walkthrough',
      pause: 'Pause workflow walkthrough',
      resume: 'Resume workflow walkthrough',
      manual: 'Select a phase manually',
      boundaryTitle: 'Responsibility boundary',
      boundaryBody:
        'The coding agent owns understanding, scenario planning, and fixes. A3S Test does not call a second LLM for decisions; it validates and executes one typed action. The public demo above still stores data only in this tab.',
      steps: [
        {
          label: 'Input contract',
          status: 'INPUT CONTRACT',
          title:
            'Place the PRD, design reference, and running page in one context',
          body: 'Requirements define the outcome, the design reference constrains visual intent, and the browser provides current facts. Each input keeps its own boundary.',
          sourceTitle: 'Three inputs',
          sources: [
            {
              label: 'checkout-requirements.md',
              detail: 'business rules · observable success',
            },
            {
              label: 'design-reference.png',
              detail: 'visual target · layout intent',
            },
            {
              label: 'localhost:3000/checkout',
              detail: 'running UI · current revision',
            },
          ],
          processTitle: 'Build the task contract',
          processLead: 'First define what the page can prove',
          processRows: [
            { label: 'Goal', value: 'Reach confirmation after submit' },
            { label: 'Success', value: '“Order confirmed” heading is visible' },
            { label: 'Scope', value: '/checkout · same-origin page' },
            {
              label: 'Authority',
              value: 'Read evidence; no source-edit grant',
            },
          ],
          outputTitle: 'Task contract',
          outputLines: [
            'goal        observable',
            'reference   bounded',
            'target      running page',
            'authority   unchanged',
          ],
        },
        {
          label: 'Understand UI',
          status: 'UI UNDERSTANDING',
          title: 'Read semantics, states, and geometry against design intent',
          body: 'Page Context and UI Understanding extract accessible semantics, interaction states, layout relationships, and source candidates from the real render. The design image stays bounded reference material.',
          sourceTitle: 'Current page facts',
          sources: [
            {
              label: 'render revision 18',
              detail: 'DOM · accessibility tree · style',
            },
            {
              label: 'Page Context',
              detail: 'components · locators · source hints',
            },
            {
              label: 'design reference',
              detail: 'region comparison · intended hierarchy',
            },
          ],
          processTitle: 'Interface model',
          processLead: 'Executable UI semantics for the current revision',
          processRows: [
            { label: 'Semantics', value: 'button · “Place order”' },
            { label: 'States', value: 'default · hover · disabled' },
            { label: 'Geometry', value: 'viewport box · layout graph' },
            { label: 'Ownership', value: 'CheckoutForm · source candidate' },
          ],
          outputTitle: 'Verifiable target',
          outputLines: [
            'role        button',
            'name        “Place order”',
            'locator     role(button, name)',
            'criterion   confirmation visible',
          ],
        },
        {
          label: 'Plan scenarios',
          status: 'SCENARIO PLAN',
          title:
            'The coding agent turns success criteria into executable scenarios',
          body: 'The agent combines the task contract, latest observation, and driver capabilities to plan the happy path and failure branches. A3S Test supplies execution constraints, not another model decision-maker.',
          sourceTitle: 'Planning inputs',
          sources: [
            {
              label: 'goal + success',
              detail: 'objective and success criteria',
            },
            { label: 'UI model', detail: 'actionable targets and page state' },
            {
              label: 'driver schema',
              detail: 'actions this surface can prove',
            },
          ],
          processTitle: 'Scenario planning',
          processLead: 'Work backward from an observable result',
          processRows: [
            { label: 'Planner', value: 'the context-owning coding agent' },
            { label: 'Happy path', value: 'submit → confirmation state' },
            { label: 'Failure path', value: 'validation remains visible' },
            {
              label: 'Decision source',
              value: 'latest observation; no second LLM',
            },
          ],
          outputTitle: 'Scenario draft',
          outputLines: [
            'scenario    submit-order',
            'precondition checkout ready',
            'path        submit → confirmation',
            'failure     validation stays visible',
          ],
        },
        {
          label: 'Explore',
          status: 'AGENT SESSION',
          title: 'Execute one typed action at a time in a persistent session',
          body: 'The browser persists, but refs bind only to the latest observation. Re-observe after every action; stale references and unauthorized navigation fail closed.',
          sourceTitle: 'Session inputs',
          sources: [
            {
              label: 'session checkout',
              detail: 'goal · success · origin policy',
            },
            { label: 'observation_id 1', detail: 'latest semantic page state' },
            {
              label: '@e1 [button]',
              detail: 'Place order · observation-bound ref',
            },
          ],
          processTitle: 'Observe and act loop',
          processLead: 'Start → Observe → Decide → Act → Observe',
          processRows: [
            { label: 'Start', value: 'open a session with an explicit goal' },
            { label: 'Observe', value: 'receive a new observation and refs' },
            { label: 'Decide', value: 'coding agent selects the next step' },
            { label: 'Act', value: 'execute once, then observe again' },
          ],
          outputTitle: 'Typed commands',
          outputLines: [
            'agent start /checkout --session checkout',
            'agent observe --session checkout --json',
            'agent click @e1 --observation 1',
            'agent observe --session checkout --json',
          ],
        },
        {
          label: 'Preserve ACL',
          status: 'DETERMINISTIC ACL',
          title: 'Distill the proven stable path into deterministic regression',
          body: 'Temporary exploration refs do not enter the suite. ACL retains stable locators, explicit waits, assertions, and necessary evidence, then checks before it runs.',
          sourceTitle: 'Proven path',
          sources: [
            {
              label: 'events.jsonl',
              detail: 'actual action and observation order',
            },
            { label: 'stable locator', detail: 'role · name · CSS contract' },
            {
              label: 'observable assertion',
              detail: 'visible confirmation state',
            },
          ],
          processTitle: 'Regression distillation',
          processLead: 'Admit only steps that replay in a fresh browser',
          processRows: [
            {
              label: 'Action',
              value: 'stable semantics, never a temporary ref',
            },
            { label: 'Wait', value: 'bounded stability window' },
            { label: 'Assert', value: 'result visible directly on the page' },
            { label: 'Cleanup', value: 'close the session-owned surface' },
          ],
          outputTitle: 'checkout.acl',
          outputLines: [
            'click       role(button, “Place order”)',
            'expect      text “Order confirmed”',
            'a3s-test check tests/e2e/checkout.acl',
            'a3s-test run tests/e2e/checkout.acl',
          ],
        },
        {
          label: 'Close evidence',
          status: 'EVIDENCE → CI',
          title:
            'Classify failure, fix, then verify and replay the same contract',
          body: 'Results are classified as product, specification, or infrastructure failures. After the coding agent fixes the issue, A3S Test verifies the changed page and carries the same ACL into CI.',
          sourceTitle: 'Run evidence',
          sources: [
            { label: 'screenshot', detail: 'final visual state' },
            {
              label: 'a11y + runtime',
              detail: 'semantics · console · page errors',
            },
            {
              label: 'report + event log',
              detail: 'verdict · actions · cleanup',
            },
          ],
          processTitle: 'Diagnosis and replay',
          processLead: 'Let evidence choose the next step',
          processRows: [
            {
              label: 'Classify',
              value: 'product / specification / infrastructure',
            },
            { label: 'Fix', value: 'performed by an authorized coding agent' },
            {
              label: 'Verify',
              value: 're-observe and assert on the changed page',
            },
            { label: 'Replay', value: 'run the same ACL locally and in CI' },
          ],
          outputTitle: 'Verification record',
          outputLines: [
            'classification product',
            'fix_owner     coding-agent',
            'verify        fresh-browser + CI replay',
            'cleanup       owned surface closed',
          ],
        },
      ],
      evidenceTitle: 'Every run keeps the smallest reviewable evidence set',
      evidenceItems: [
        { label: 'SCREENSHOT', detail: 'final visual state' },
        { label: 'ACCESSIBILITY', detail: 'semantics and operability' },
        { label: 'CONSOLE', detail: 'browser log stream' },
        { label: 'PAGE ERRORS', detail: 'uncaught runtime failures' },
        { label: 'HAR · TRACE · VIDEO', detail: 'captured only when needed' },
      ],
      evidenceNote:
        'Failures are classified as product / specification / infrastructure. HAR, trace, and video stay opt-in. Every session ends with finish or abort and cleans up the resources it owns.',
    },
    installTitle: 'Install the execution core with one command',
    installBody:
      'The CLI and Agent Skill run sessions and ACL. Add Test Kit only when selecting, drawing, capturing, or sketching inside the page helps.',
    testkitInstallLink: 'Add Web Test Kit when needed',
    installTabs: 'Choose an installation platform',
    installPackage: 'CLI + Agent Skill',
    installNote:
      'The installer verifies the release archive SHA-256 and keeps the CLI and Skill on one version.',
    installCandidateNote:
      'These docs are preparing the next version. This command still pins the published stable release.',
    copy: 'Copy command',
    copied: 'Command copied',
    copyError: 'Copy failed. Select the command manually.',
    benchmark: {
      title: 'Same tasks. Compare completion, safety, and cost.',
      body: 'This comparison isolates the execution layer: both candidates use one deterministic solver and the same browser foundation, with official MiniWoB reward as the only success verdict.',
      tableCaption:
        'UI execution-layer comparison between A3S Test and direct agent-browser',
      dimension: 'Measure',
      candidate: 'A3S Test 1.0.0',
      baseline: 'Direct agent-browser 0.26.0',
      metrics: {
        success: 'Task success',
        staleReference: 'Stale-reference protection',
        evidence: 'Built-in run evidence',
        latency: 'Paired common-success median',
      },
      labels: {
        mainRuns: 'main runs',
        staleRejected: 'old refs rejected',
        pageMutations: 'page mutations',
        artifactRuns: 'runs with built-in evidence files',
        versusDirect: 'versus the direct client',
        hostBaseline: 'host-local baseline',
        lockedProtocol: 'Locked MiniWoB++ protocol',
        tasks: 'tasks',
        repetitions: 'repetitions',
      },
      limitation:
        'This is single-host development evidence, not a model-reasoning or universal-performance claim. Drag and wheel probes timed out for both candidates and are excluded from the main success rate.',
      reportLink: 'Read the full protocol, raw data, and reproduction steps',
    },
    packetTitle: 'Give the agent more than “something is wrong here”',
    packetBody:
      'Test Kit combines human intent with bounded context the browser already computed. The agent can see the target, its likely owner, and the exact page revision that produced the evidence.',
    packetLabel: 'Example handoff packet',
    packetLines: [
      'protocol    a3s.test.repair/1',
      'page        /checkout · revision 18',
      'selection   button “Submit order”',
      'source      TestKitExperience.tsx',
      'intent      Increase text contrast',
      'context     role · locator · viewport geometry',
      'authority   human submitted',
    ],
    packetTrust:
      'Page-derived content remains untrusted evidence. Selecting, capturing, or saving a draft never grants source-edit authority.',
    packetLink: 'Inspect Page Context, authority, and fail-closed rules',
    quickStartTitle: 'Run one real page in three steps',
    quickStartBody:
      'Keep the application running as usual, then open a session around one explicit goal. Execute one typed action at a time from the latest observation.',
    quickStartSteps: [
      {
        title: 'Run your page',
        body: 'Use the project command you already have. A3S Test does not need a custom build step.',
        command: 'npm run dev',
      },
      {
        title: 'Start a session with a visible outcome',
        body: 'The goal and success condition must be observable from the page.',
        command:
          'a3s-test agent start http://127.0.0.1:3000 \\\n  --session ui \\\n  --goal "Reproduce the submit failure" \\\n  --success "The confirmation heading is visible"',
      },
      {
        title: 'Observe before acting',
        body: 'Use fresh refs, verify the result, then distill the stable path into ACL.',
        command: 'a3s-test agent observe --session ui --interactive --json',
      },
    ],
    quickStartLink: 'Open the complete quick start',
    faqTitle: 'Answers that should shape the decision',
    faqBody:
      'Clear boundaries matter more than putting every capability on one page.',
    faqItems: [
      {
        question: 'Does ordinary Web testing require Test Kit?',
        answer:
          'No. The CLI can drive a browser directly. Add Test Kit only when component ownership, source candidates, page geometry, visual references, or human marking materially helps the task.',
      },
      {
        question: 'Does page capture request whole-screen permission?',
        answer:
          'No. Test Kit captures browser-page content and lets the user crop inside the page. It does not invoke whole-screen sharing or operating-system screen recording.',
      },
      {
        question: 'Does selecting an element let the agent edit source?',
        answer:
          'No. A selection and a draft are evidence only. A finding enters the repair queue only after explicit submission, and workspace mutation still belongs to a separately authorized coding agent.',
      },
      {
        question: 'Can a marker drift after scrolling or a page update?',
        answer:
          'Markers recompute from the current scroll position. After a revision change, refs and geometry that cannot be proven current expire instead of silently resolving to another element.',
      },
      {
        question: 'Why keep both agent sessions and ACL?',
        answer:
          'Sessions explore unknown paths from each fresh observation. ACL retains only proven actions, waits, assertions, and evidence so the same path can repeat locally and in CI.',
      },
    ],
    ctaTitle: 'Start with one real page',
    ctaBody:
      'Prove one session with an observable success condition. Add Test Kit only when richer page context helps.',
    quickStart: 'Run your first test',
    testkitGuide: 'Add Test Kit',
    footer: 'Act from the current page. Turn proven paths into regressions.',
    experience: {
      stageAria: 'Live A3S Test Kit experience',
      boundaryName: 'Checkout experience',
      sample: 'Interactive demo',
      shop: 'A3S Shop',
      checkoutTitle: 'Review order',
      checkoutProgress: ['Cart', 'Review', 'Payment', 'Complete'],
      customerTitle: 'Delivery details',
      customerName: 'Alex Chen · +1 555 0100',
      customerAddress: '1001 Interface Way, San Francisco, CA 94107',
      productsTitle: 'Order items',
      productName: 'A3S autonomous testing suite',
      productVariant: 'Team · annual license',
      quantity: 'Quantity 1',
      subtotal: '$1,298.00',
      totalDue: '$1,248.00',
      summaryTitle: 'Order summary',
      productTotal: 'Products',
      delivery: 'Delivery',
      deliveryValue: '$0.00',
      discount: 'Discount',
      discountValue: '−$50.00',
      payable: 'Total due',
      paymentTitle: 'Payment method',
      paymentMethod: 'Company test account',
      submit: 'Place order',
      submitted: 'Demo order submitted. Page context refreshed.',
      contextTitle: 'Page context',
      refresh: 'Refresh',
      connecting: 'Reading the real page context…',
      contextUnavailable: 'Page context is unavailable. Refresh to try again.',
      notAvailable: 'n/a',
      selected: 'Current target',
      revision: 'Page revision',
      role: 'Role',
      name: 'Name',
      geometry: 'Viewport box',
      locator: 'Primary locator',
      source: 'Component source',
      reviewTitle: 'Mark a page issue',
      reviewBody:
        'Select an element and state the expected result. Save related issues as one batch.',
      openReview: 'Start marking',
      reviewStarted: 'Marking is active',
      live: 'LIVE',
      localOnly:
        'This demo keeps issues in the current tab. It does not connect to a repair agent or edit source.',
      evidenceTitle: 'Issues on this page',
      evidenceWaiting: 'Nothing saved',
      evidenceReady: 'Saved in this tab',
      receiptId: 'RECORD ID',
      receiptStatus: 'SAVED IN',
      receiptFindings: 'ISSUES',
      receiptMemory: 'current tab',
      receiptIdle: 'nothing saved',
      findingUnit: 'issue',
      findingsUnit: 'issues',
      noFinding: 'No saved issues',
      renderedStatus: 'Render complete',
      contextStatus: 'Context bound',
      evidenceStatus: 'Saved locally',
      motionSteps: [
        'Read page',
        'Bind target',
        'Describe issue',
        'Build batch',
        'Save in tab',
      ],
      scanSummary: 'DOM · A11Y · XY',
      targetMarker: 'target',
      motionFinding: '“Place order” bound',
      motionRequest:
        'Increase label contrast. Keep size and position unchanged.',
      motionPacket: '1 issue · current revision bound',
      motionContext: 'Live context',
      motionContextValue: 'button · Place order',
      motionAdd: 'Add to batch',
      motionSend: 'Save in tab',
      motionReady: 'Issue saved in the current tab',
      motionPause: 'Pause walkthrough',
      motionResume: 'Resume walkthrough',
    },
  },
};
