import type { ExperienceCopy, Locale, LocalizedCopy } from './home-copy-types';

export type {
  CapabilityGroupId,
  ExperienceCopy,
  Locale,
} from './home-copy-types';

export const homeCopy: Record<Locale, LocalizedCopy> = {
  zh: {
    heroTitle: ['基于真实页面行动', '把结果固化为回归'],
    heroBody:
      'A3S Test 把当前浏览器修订、类型化动作、节点到源码映射和验证证据连成一条可信闭环。编码 Agent 先看清页面，再执行最小动作，最后把跑通路径写成 ACL。',
    startExperience: '在本页标记一个问题',
    readDocs: '运行第一个测试',
    installTitle: '只安装当前需要的部分',
    installBody:
      '运行会话与 ACL 请安装 CLI 和 Agent Skill；在页面中点选、框选、截图或画草图请安装 Test Kit。',
    testkitInstallLink: '安装 Web Test Kit',
    installTabs: '选择安装平台',
    installPackage: 'CLI + Agent Skill',
    installNote: '安装器校验发布归档的 SHA-256，并保持 CLI 与 Skill 版本一致。',
    installCandidateNote:
      '当前文档已进入下一版本准备阶段。此命令仍固定安装已发布的稳定版。',
    copy: '复制命令',
    copied: '命令已复制',
    copyError: '复制失败，请手动选择命令',
    proofTitle: '先分清期望与事实',
    proofBody:
      'PRD 和设计稿描述应该发生什么，浏览器只证明当前实际渲染了什么。人工审阅后，Surface Contract 才能把两者变成可核对的明确期望；A3S Test 为每个差异保留来源、页面修订和证据。',
    contractPanelLabel: '产品期望与当前页面的核对路径',
    contractExpectedLabel: '产品期望',
    contractObservedLabel: '当前事实',
    contractPrdTitle: '应该完成什么',
    contractPrdBody: '用户结果、文案、业务约束与尚待决定的事项。',
    contractDesignTitle: '应该如何呈现',
    contractDesignBody: '区域层级、相互关系、尺寸、位置与视觉约束。',
    contractPageTitle: '现在实际呈现什么',
    contractPageBody: '本次修订的语义、状态、组件、定位器与几何。',
    contractReviewTitle: '人工确认候选',
    contractReviewBody: '选择可采纳的要求，处理冲突与未决事项。',
    contractCompareTitle: '核对真实页面',
    contractCompareBody: '逐项检查已确认期望与真实页面。',
    contractReportTitle: '保留可复查差异',
    contractReportBody: '记录来源、决定、页面修订与证据。',
    contractDisclaimer:
      'PRD 和设计稿产生的是期望候选，不是浏览器可访问树。只有经人工审阅的候选才能进入 Surface Contract，页面事实仍由当前浏览器修订提供。',
    contractGuide: '了解界面契约如何生成',
    capabilitiesTitle: '从页面事实到 ACL 的最短可信闭环',
    capabilitiesBody:
      '每一步只承担一种责任。页面提供当前事实，Core 准入动作，Test Kit 在需要时连接源码，验证读取更新后的页面，最后才把稳定路径固化为回归。',
    capabilities: [
      {
        title: '读取渲染后事实',
        body: '组合浏览器可访问语义与有界 Page Context，生成绑定当前修订的观察。',
        code: '01 · OBSERVE',
      },
      {
        title: '准入一个类型化动作',
        body: '用 Schema、目标类型、会话能力、来源和策略检查动作，再交给界面驱动。',
        code: '02 · ADMIT',
      },
      {
        title: '定位负责源码',
        body: '需要修改时，用显式组件归属和排序后的源码跨度连接可见节点与实现。',
        code: '03 · SOURCE',
      },
      {
        title: '验证更新后的页面',
        body: '重新读取更高页面修订，只保存能证明成功条件的断言与自有证据。',
        code: '04 · VERIFY',
      },
      {
        title: '固化为 ACL',
        body: '把跑通路径的最小动作、等待、断言和证据写成可重复套件。',
        code: '05 · PRESERVE',
      },
    ],
    capabilityLedgerTitle: '四个技术机制支撑整条闭环',
    capabilityLedgerBody:
      '这里展示决定 A3S Test 工作方式的实现边界。具体动作、字段和错误行为继续放在完整能力参考中按需查询。',
    capabilityReference: '查看完整能力的入口、输出、证据和失败边界',
    capabilityItemCount: '项核心实现',
    capabilityGroups: [
      {
        id: 'context',
        code: 'RENDERED FACTS',
        title: '渲染后页面上下文',
        summary: '从浏览器已经计算出的语义、布局和状态中生成有界事实。',
        href: '/concepts/page-context.html',
        linkLabel: '查看 Page Context 字段、预算与失效规则',
        items: [
          {
            signal: 'AX · DOM · LAYOUT',
            title: '组合浏览器事实',
            body: '可访问快照负责角色、名称和原生状态；Test Kit 补充组件、定位器、几何、布局、样式和动效。',
          },
          {
            signal: 'REVISION · @eN · @cN · @uN',
            title: '观察绑定身份',
            body: '页面变化推进单调修订。@eN 与 @cN 只在所属观察中可操作，@uN 永远只读。',
          },
          {
            signal: 'BOUNDARY · SOURCE MAP',
            title: '显式源码归属',
            body: '组件边界、DOM owner 与可选 Source Map v3 生成排序后的源码候选，不读取框架私有状态。',
          },
        ],
      },
      {
        id: 'safety',
        code: 'TYPED CORE',
        title: '类型化准入与失败关闭',
        summary: '自然语言不能直接获得浏览器、网络、证据或工作区权限。',
        href: '/concepts/authority-and-safety.html',
        linkLabel: '查看权限、安全和失败关闭规则',
        items: [
          {
            signal: 'ACTION · SCHEMA · POLICY',
            title: '一个动作一个边界',
            body: '动作先校验封闭类型、字段、目标、能力和策略，未知字段或不支持行为不会到达驱动。',
          },
          {
            signal: 'FACT · ADVICE · HUMAN · EDIT',
            title: '四层独立权限',
            body: '浏览器事实、模型建议、人工授权和源码修改彼此不能冒充，verdict 仍由确定性规则负责。',
          },
          {
            signal: 'PROCESS · ORIGIN · ARTIFACT',
            title: '精确运行时所有权',
            body: '来源、网络、进程树和证据目录分别准入，只清理本次运行创建的资源。',
          },
        ],
      },
      {
        id: 'repair',
        code: 'SOURCE-AWARE REVIEW',
        title: '源码感知的人工修复',
        summary: '评审者指出真实页面问题，明确发送后才交给拥有工作区的 Agent。',
        href: '/guide/repairs.html',
        linkLabel: '查看标记、发送、修复与验收流程',
        items: [
          {
            signal: 'ELEMENT · REGION · DRAW · CAPTURE',
            title: '一个右侧评审界面',
            body: '点选、文本、多选、框选、手绘、画板和浏览器内容截图都在同一侧栏完成，不堆叠弹窗。',
          },
          {
            signal: 'CONTEXT · SOURCE · EXPLICIT SEND',
            title: '发送时绑定最新上下文',
            body: 'finding 在明确发送时附带当前修订、组件、定位器、几何、源码候选和有界附近证据。',
          },
          {
            signal: 'BEFORE · AFTER · ACCEPT',
            title: '新页面验证与人工验收',
            body: '修改后重新定位目标并比较断言、截图、console 和 page errors，最后由人接受或重新打开。',
          },
        ],
      },
      {
        id: 'evidence',
        code: 'EVIDENCE & ACL',
        title: '可审计证据与确定性回归',
        summary: '让探索结果可解释、可复现，并最终脱离临时 Agent 决策。',
        href: '/guide/workflows.html',
        linkLabel: '查看 Agent 会话与 ACL 回归工作流',
        items: [
          {
            signal: 'SESSION · EVENTS · REPORT',
            title: '追加式会话记录',
            body: '目标、观察、类型化动作、证据和终态报告保留在会话目录，失败归属可以复查。',
          },
          {
            signal: 'ASSERT · STABILITY · EVIDENCE',
            title: '最小确定性验证',
            body: '断言读取浏览器实际状态，稳定窗口只重复只读断言，不自动重放普通动作。',
          },
          {
            signal: 'CHECK · RUN · CI',
            title: 'ACL 固化已证明路径',
            body: '关闭式清单在执行前静态准入，再在本地和 CI 重复明确动作、等待、断言与证据。',
          },
        ],
      },
    ],
    workflowTitle: '先探索，再回归',
    workflowBody:
      '路径未知时，Agent 会话保留浏览器状态并从最新观察选择下一步。路径证明后，只把最小稳定形式写入 ACL。',
    workflowAgent: '探索未知路径',
    workflowAgentBody:
      '每次读取当前页面，只执行一个动作，用于复现问题、理解陌生流程并证明成功条件。',
    workflowAcl: '重复已证明路径',
    workflowAclBody:
      '把明确动作、等待、断言和证据写成关闭式套件，在本地、CI 和界面契约检查中运行。',
    workflowAgentLink: '了解 Agent 会话',
    workflowAclLink: '编写 ACL 套件',
    workflowObserve: '当前事实',
    workflowDecide: '类型化动作',
    workflowAct: '新页面证据',
    workflowProve: 'ACL 回归',
    boundaryTitle: '事实、建议、授权与修改互不冒充',
    boundaryBody:
      '浏览器提供当前事实，模型只能提出带来源候选，人决定是否发送修复，拥有工作区的编码 Agent 才能改源码，A3S Test 最后从更新后的页面验证。',
    boundaryFacts: '浏览器事实',
    boundaryFactsBody: '当前 DOM、可访问语义、状态、几何、组件与断言结果。',
    boundaryAdvice: '模型建议',
    boundaryAdviceBody:
      '视觉定位和设计审查给出带来源、置信度和预算的候选，不决定测试结果。',
    boundaryHuman: '人工授权',
    boundaryHumanBody: '确认目标、期望结果、冲突关系，以及单项或批量发送范围。',
    boundaryRepair: '修改与验收',
    boundaryRepairBody:
      '编码 Agent 只在授权范围内修改，A3S Test 用新页面验证，再交回人工验收。',
    surfacesTitle: '一个 Core，三类界面驱动',
    surfacesBody:
      'Core 统一动作、策略、证据、结果和生命周期。Web、GUI 与 TUI 驱动分别拥有感知、执行和清理，不支持的能力直接关闭失败。',
    surfaceWeb: 'Web',
    surfaceWebBody:
      'Agent 会话与 ACL 通过 A3S Browser 或兼容独立浏览器运行，并可接入 Test Kit Page Context。',
    surfaceGui: 'GUI',
    surfaceGuiBody:
      'macOS CUA 已在真实 arm64 主机验证感知、权限与清理。其他桌面后端仍在独立审核。',
    surfaceTui: 'TUI',
    surfaceTuiBody:
      'ACL 通过自有 PTY / ConPTY 进程树运行，并使用有界终端语义与清理规则。',
    ctaTitle: '从一个真实页面开始',
    ctaBody:
      '先用 CLI 跑通一个带可观察成功条件的会话。需要组件、源码、坐标或人工标记时再接入 Test Kit，最后把证明过的路径写成 ACL。',
    quickStart: '运行第一个测试',
    testkitGuide: '接入 Test Kit',
    architecture: '查看技术架构',
    footer: '依据当前页面行动，把证明过的路径变成回归。',
    experience: {
      stageAria: 'A3S Test Kit 实时体验',
      boundaryName: '订单确认体验',
      sample: '交互演示',
      shop: 'A3S Shop',
      checkoutTitle: '确认订单',
      checkoutProgress: ['购物车', '确认订单', '支付', '完成'],
      customerTitle: '收货信息',
      customerName: '张三 · 138 0000 0000',
      customerAddress: '北京市海淀区中关村大街 1 号 A3S 大厦 1001 室',
      productsTitle: '商品清单',
      productName: 'A3S 自动化测试套件',
      productVariant: '团队版 · 年度许可',
      quantity: '数量 1',
      subtotal: '¥1,298.00',
      totalDue: '¥1,248.00',
      summaryTitle: '订单金额',
      productTotal: '商品总额',
      delivery: '运费',
      deliveryValue: '¥0.00',
      discount: '优惠',
      discountValue: '−¥50.00',
      payable: '实付金额',
      paymentTitle: '支付方式',
      paymentMethod: '企业测试账户',
      submit: '提交订单',
      submitted: '演示订单已提交，页面上下文已刷新。',
      contextTitle: '页面上下文',
      refresh: '刷新',
      connecting: '正在读取真实页面上下文…',
      contextUnavailable: '未读到页面上下文，请刷新重试。',
      notAvailable: '暂无',
      selected: '当前目标',
      revision: '页面修订',
      role: '角色',
      name: '名称',
      geometry: '视口几何',
      locator: '首选定位器',
      source: '组件来源',
      reviewTitle: '标记页面问题',
      reviewBody: '点选元素并写清期望结果。多个相关问题可以一起整理后保存。',
      openReview: '开始标记',
      reviewStarted: '标记工具已打开',
      live: '实时',
      localOnly:
        '此演示只把问题保存在当前标签页，不连接修复 Agent，也不会修改源码。',
      evidenceTitle: '本页问题',
      evidenceWaiting: '尚未保存',
      evidenceReady: '已保存到本页',
      receiptId: '记录 ID',
      receiptStatus: '保存位置',
      receiptFindings: '问题数量',
      receiptMemory: '当前标签页',
      receiptIdle: '尚未保存',
      findingUnit: '个问题',
      findingsUnit: '个问题',
      noFinding: '尚未保存问题',
      renderedStatus: '渲染完成',
      contextStatus: '上下文已绑定',
      evidenceStatus: '本地保存',
      motionSteps: ['读取页面', '绑定目标', '说明问题', '组成批次', '保存本页'],
      scanSummary: 'DOM · 语义 · 坐标',
      targetMarker: '目标',
      motionFinding: '已绑定“提交订单”',
      motionRequest: '提高按钮文字对比度，保持尺寸与位置不变。',
      motionPacket: '1 个问题 · 已绑定当前修订',
      motionContext: '实时上下文',
      motionContextValue: 'button · 提交订单',
      motionAdd: '加入批次',
      motionSend: '保存到本页',
      motionReady: '问题已保存到当前标签页',
      motionPause: '暂停自动演示',
      motionResume: '继续自动演示',
    },
  },
  en: {
    heroTitle: ['Act on what rendered.', 'Preserve what worked.'],
    heroBody:
      'A3S Test connects the current browser revision, typed actions, rendered-node source mapping, and verification evidence in one trustworthy loop. A coding agent reads the page first, makes the smallest move, then preserves the proven path as ACL.',
    startExperience: 'Mark an issue on this page',
    readDocs: 'Run your first test',
    installTitle: 'Install only what this task needs',
    installBody:
      'Install the CLI and Agent Skill for sessions and ACL. Install Test Kit to select, draw, capture, or sketch inside a development page.',
    testkitInstallLink: 'Install Web Test Kit',
    installTabs: 'Choose an installation platform',
    installPackage: 'CLI + Agent Skill',
    installNote:
      'The installer verifies the release archive SHA-256 and keeps the CLI and Skill on one version.',
    installCandidateNote:
      'These docs are preparing the next version. This command still pins the published stable release.',
    copy: 'Copy command',
    copied: 'Command copied',
    copyError: 'Copy failed. Select the command manually.',
    proofTitle: 'Separate expectations from facts first',
    proofBody:
      'A PRD or design describes what should happen. The browser proves only what rendered now. After human review, a Surface Contract turns expectations into explicit checks, and A3S Test retains the source, page revision, and evidence for every difference.',
    contractPanelLabel: 'Path from product expectation to current page fact',
    contractExpectedLabel: 'Product expectation',
    contractObservedLabel: 'Current fact',
    contractPrdTitle: 'What should the user accomplish?',
    contractPrdBody:
      'User outcomes, copy, business constraints, and open decisions.',
    contractDesignTitle: 'How should it appear?',
    contractDesignBody:
      'Region hierarchy, relationships, dimensions, position, and visual constraints.',
    contractPageTitle: 'What renders now?',
    contractPageBody:
      'Semantics, state, components, locators, and geometry for this revision.',
    contractReviewTitle: 'Review the candidates',
    contractReviewBody:
      'Admit valid requirements and resolve conflicts or open decisions.',
    contractCompareTitle: 'Compare the rendered page',
    contractCompareBody:
      'Check each reviewed expectation against current browser facts.',
    contractReportTitle: 'Retain inspectable differences',
    contractReportBody:
      'Record provenance, decisions, page revision, and evidence.',
    contractDisclaimer:
      'PRDs and designs produce expectation candidates, not a browser accessibility tree. Only reviewed candidates enter a Surface Contract, and current rendered facts still come from the browser revision.',
    contractGuide: 'Learn how interface contracts are generated',
    capabilitiesTitle: 'The shortest trustworthy path from page fact to ACL',
    capabilitiesBody:
      'Each stage owns one responsibility. The page supplies current facts, Core admits an action, Test Kit connects source when needed, verification reads the changed page, and only then does the stable path become regression coverage.',
    capabilities: [
      {
        title: 'Read post-render facts',
        body: 'Combine browser accessibility semantics with bounded Page Context in one revision-bound observation.',
        code: '01 · OBSERVE',
      },
      {
        title: 'Admit one typed action',
        body: 'Validate schema, target type, session capability, origin, and policy before a surface driver runs.',
        code: '02 · ADMIT',
      },
      {
        title: 'Find the owning source',
        body: 'When code must change, connect the visible node to explicit component ownership and ranked source spans.',
        code: '03 · SOURCE',
      },
      {
        title: 'Verify the changed page',
        body: 'Read a newer page revision and retain only the assertions and owned evidence that prove success.',
        code: '04 · VERIFY',
      },
      {
        title: 'Preserve it as ACL',
        body: 'Encode the smallest proven actions, waits, assertions, and evidence as a repeatable suite.',
        code: '05 · PRESERVE',
      },
    ],
    capabilityLedgerTitle: 'Four technical mechanisms support the loop',
    capabilityLedgerBody:
      'These are the implementation boundaries that define how A3S Test works. Use the complete capability reference only when you need exact actions, fields, and failure behavior.',
    capabilityReference:
      'Inspect every capability entry point, output, evidence rule, and failure boundary',
    capabilityItemCount: 'core mechanisms',
    capabilityGroups: [
      {
        id: 'context',
        code: 'RENDERED FACTS',
        title: 'Post-render page context',
        summary:
          'Derive bounded facts from semantics, layout, and state the browser already computed.',
        href: '/concepts/page-context.html',
        linkLabel: 'Inspect Page Context fields, budgets, and expiry rules',
        items: [
          {
            signal: 'AX · DOM · LAYOUT',
            title: 'Combine browser facts',
            body: 'Accessibility owns roles, names, and native state. Test Kit adds components, locators, geometry, layout, style, and motion.',
          },
          {
            signal: 'REVISION · @eN · @cN · @uN',
            title: 'Bind public identity to observation',
            body: 'Page changes advance a monotonic revision. @eN and @cN are actionable only in their observation, while @uN is always read-only.',
          },
          {
            signal: 'BOUNDARY · SOURCE MAP',
            title: 'Declare source ownership',
            body: 'Component boundaries, DOM owners, and optional Source Map v3 produce ranked candidates without reading framework private state.',
          },
        ],
      },
      {
        id: 'safety',
        code: 'TYPED CORE',
        title: 'Typed admission and fail-closed safety',
        summary:
          'Natural language never directly acquires browser, network, evidence, or workspace authority.',
        href: '/concepts/authority-and-safety.html',
        linkLabel: 'Inspect authority, safety, and fail-closed behavior',
        items: [
          {
            signal: 'ACTION · SCHEMA · POLICY',
            title: 'One action, one boundary',
            body: 'Closed variants validate fields, targets, capabilities, and policy before unsupported or unknown input can reach a driver.',
          },
          {
            signal: 'FACT · ADVICE · HUMAN · EDIT',
            title: 'Keep four authorities independent',
            body: 'Browser facts, model advice, human authorization, and source mutation cannot impersonate one another. Deterministic rules own verdicts.',
          },
          {
            signal: 'PROCESS · ORIGIN · ARTIFACT',
            title: 'Own runtime resources exactly',
            body: 'Origins, network, process trees, and artifact roots are admitted separately, and cleanup touches only run-owned resources.',
          },
        ],
      },
      {
        id: 'repair',
        code: 'SOURCE-AWARE REVIEW',
        title: 'Source-aware human repair',
        summary:
          'A reviewer identifies a real page problem before a workspace-owning agent receives it.',
        href: '/guide/repairs.html',
        linkLabel: 'Inspect marking, submission, repair, and acceptance',
        items: [
          {
            signal: 'ELEMENT · REGION · DRAW · CAPTURE',
            title: 'Use one right-side review surface',
            body: 'Element, text, multi-select, region, freehand, board, and browser-page capture stay in one panel without stacked dialogs.',
          },
          {
            signal: 'CONTEXT · SOURCE · EXPLICIT SEND',
            title: 'Bind current context at submission',
            body: 'An explicitly sent finding carries the current revision, component, locator, geometry, source candidates, and bounded nearby evidence.',
          },
          {
            signal: 'BEFORE · AFTER · ACCEPT',
            title: 'Verify fresh and return to a person',
            body: 'Repair re-resolves the target and compares assertions, screenshots, console, and page errors before human acceptance or reopening.',
          },
        ],
      },
      {
        id: 'evidence',
        code: 'EVIDENCE & ACL',
        title: 'Auditable evidence and deterministic regression',
        summary:
          'Make exploration explainable and reproducible, then remove dependence on temporary agent decisions.',
        href: '/guide/workflows.html',
        linkLabel: 'Inspect agent-session and ACL regression workflows',
        items: [
          {
            signal: 'SESSION · EVENTS · REPORT',
            title: 'Retain an append-only session record',
            body: 'Goals, observations, typed actions, evidence, and the terminal report remain inspectable with clear failure ownership.',
          },
          {
            signal: 'ASSERT · STABILITY · EVIDENCE',
            title: 'Verify the smallest deterministic claim',
            body: 'Assertions read browser state directly. Stability windows repeat only read-only assertions and never replay ordinary actions automatically.',
          },
          {
            signal: 'CHECK · RUN · CI',
            title: 'Preserve proven paths as ACL',
            body: 'A closed manifest passes static admission before explicit actions, waits, assertions, and evidence repeat locally or in CI.',
          },
        ],
      },
    ],
    workflowTitle: 'Explore first. Regress second.',
    workflowBody:
      'When the path is unknown, an agent session keeps browser state and chooses from each current observation. After proof, preserve only the smallest stable form as ACL.',
    workflowAgent: 'Explore an unknown path',
    workflowAgentBody:
      'Read the current page and execute one action at a time to reproduce a bug, understand an unfamiliar flow, and prove the success condition.',
    workflowAcl: 'Repeat a proven path',
    workflowAclBody:
      'Encode explicit actions, waits, assertions, and evidence as a closed suite for local, CI, and Surface Contract checks.',
    workflowAgentLink: 'Learn agent sessions',
    workflowAclLink: 'Write an ACL suite',
    workflowObserve: 'Current facts',
    workflowDecide: 'Typed action',
    workflowAct: 'Fresh evidence',
    workflowProve: 'ACL regression',
    boundaryTitle: 'Facts, advice, authority, and edits stay distinct',
    boundaryBody:
      'The browser supplies current facts. Models can only propose sourced candidates. A person decides whether to submit a repair. The workspace-owning coding agent edits source, and A3S Test verifies the changed page.',
    boundaryFacts: 'Browser facts',
    boundaryFactsBody:
      'Current DOM, accessible semantics, state, geometry, components, and assertion results.',
    boundaryAdvice: 'Model advice',
    boundaryAdviceBody:
      'Visual grounding and design review return candidates with provenance, confidence, and budgets. They never set the verdict.',
    boundaryHuman: 'Human authorization',
    boundaryHumanBody:
      'Confirm the target, expected result, conflicts, and the single or batch submission scope.',
    boundaryRepair: 'Edits and acceptance',
    boundaryRepairBody:
      'The coding agent edits only within scope, A3S Test verifies a newer page, and the reviewer accepts or reopens the result.',
    surfacesTitle: 'One Core, three surface drivers',
    surfacesBody:
      'Core unifies actions, policy, evidence, results, and lifecycle. Web, GUI, and TUI drivers separately own perception, execution, and cleanup, and unsupported capability fails closed.',
    surfaceWeb: 'Web',
    surfaceWebBody:
      'Agent sessions and ACL run through A3S Browser or a compatible standalone browser, with optional Test Kit Page Context.',
    surfaceGui: 'GUI',
    surfaceGuiBody:
      'macOS CUA perception, permissions, and cleanup are verified on a real arm64 host. Other desktop backends remain under separate review.',
    surfaceTui: 'TUI',
    surfaceTuiBody:
      'ACL runs through owned PTY / ConPTY process trees with bounded terminal semantics and cleanup.',
    ctaTitle: 'Start with one real page',
    ctaBody:
      'Use the CLI to prove one session with an observable success condition. Add Test Kit only for components, source, geometry, or human marking, then preserve the proven path as ACL.',
    quickStart: 'Run your first test',
    testkitGuide: 'Add Test Kit',
    architecture: 'Review the technical architecture',
    footer: 'Act from the current page. Turn proven paths into regressions.',
    experience: {
      stageAria: 'Live A3S Test Kit experience',
      boundaryName: 'Checkout experience',
      sample: 'Interactive demo',
      shop: 'A3S Shop',
      checkoutTitle: 'Review order',
      checkoutProgress: ['Cart', 'Review', 'Payment', 'Complete'],
      customerTitle: 'Delivery details',
      customerName: 'Alex Chen · +1 555 0100',
      customerAddress: '1001 Interface Way, San Francisco, CA 94107',
      productsTitle: 'Order items',
      productName: 'A3S autonomous testing suite',
      productVariant: 'Team · annual license',
      quantity: 'Quantity 1',
      subtotal: '$1,298.00',
      totalDue: '$1,248.00',
      summaryTitle: 'Order summary',
      productTotal: 'Products',
      delivery: 'Delivery',
      deliveryValue: '$0.00',
      discount: 'Discount',
      discountValue: '−$50.00',
      payable: 'Total due',
      paymentTitle: 'Payment method',
      paymentMethod: 'Company test account',
      submit: 'Place order',
      submitted: 'Demo order submitted. Page context refreshed.',
      contextTitle: 'Page context',
      refresh: 'Refresh',
      connecting: 'Reading the real page context…',
      contextUnavailable: 'Page context is unavailable. Refresh to try again.',
      notAvailable: 'n/a',
      selected: 'Current target',
      revision: 'Page revision',
      role: 'Role',
      name: 'Name',
      geometry: 'Viewport box',
      locator: 'Primary locator',
      source: 'Component source',
      reviewTitle: 'Mark a page issue',
      reviewBody:
        'Select an element and state the expected result. Save related issues as one batch.',
      openReview: 'Start marking',
      reviewStarted: 'Marking is active',
      live: 'LIVE',
      localOnly:
        'This demo keeps issues in the current tab. It does not connect to a repair agent or edit source.',
      evidenceTitle: 'Issues on this page',
      evidenceWaiting: 'Nothing saved',
      evidenceReady: 'Saved in this tab',
      receiptId: 'RECORD ID',
      receiptStatus: 'SAVED IN',
      receiptFindings: 'ISSUES',
      receiptMemory: 'current tab',
      receiptIdle: 'nothing saved',
      findingUnit: 'issue',
      findingsUnit: 'issues',
      noFinding: 'No saved issues',
      renderedStatus: 'Render complete',
      contextStatus: 'Context bound',
      evidenceStatus: 'Saved locally',
      motionSteps: [
        'Read page',
        'Bind target',
        'Describe issue',
        'Build batch',
        'Save in tab',
      ],
      scanSummary: 'DOM · A11Y · XY',
      targetMarker: 'target',
      motionFinding: '“Place order” bound',
      motionRequest:
        'Increase label contrast. Keep size and position unchanged.',
      motionPacket: '1 issue · current revision bound',
      motionContext: 'Live context',
      motionContextValue: 'button · Place order',
      motionAdd: 'Add to batch',
      motionSend: 'Save in tab',
      motionReady: 'Issue saved in the current tab',
      motionPause: 'Pause walkthrough',
      motionResume: 'Resume walkthrough',
    },
  },
};
