export type Locale = 'zh' | 'en';

export type CapabilityGroupId = 'context' | 'core' | 'execution' | 'evidence';

export type ExperienceCopy = {
  stageAria: string;
  boundaryName: string;
  sample: string;
  shop: string;
  checkoutTitle: string;
  checkoutProgress: [string, string, string, string];
  customerTitle: string;
  customerName: string;
  customerAddress: string;
  productsTitle: string;
  productName: string;
  productVariant: string;
  quantity: string;
  subtotal: string;
  totalDue: string;
  summaryTitle: string;
  productTotal: string;
  delivery: string;
  deliveryValue: string;
  discount: string;
  discountValue: string;
  payable: string;
  paymentTitle: string;
  paymentMethod: string;
  submit: string;
  submitted: string;
  contextTitle: string;
  refresh: string;
  connecting: string;
  contextUnavailable: string;
  notAvailable: string;
  selected: string;
  revision: string;
  role: string;
  name: string;
  geometry: string;
  locator: string;
  source: string;
  reviewTitle: string;
  reviewBody: string;
  openReview: string;
  reviewStarted: string;
  live: string;
  localOnly: string;
  evidenceTitle: string;
  evidenceWaiting: string;
  evidenceReady: string;
  receiptId: string;
  receiptStatus: string;
  receiptFindings: string;
  receiptMemory: string;
  receiptIdle: string;
  findingUnit: string;
  findingsUnit: string;
  noFinding: string;
  renderedStatus: string;
  contextStatus: string;
  evidenceStatus: string;
  motionSteps: [string, string, string, string, string];
  scanSummary: string;
  targetMarker: string;
  motionFinding: string;
  motionRequest: string;
  motionPacket: string;
  motionContext: string;
  motionContextValue: string;
  motionAdd: string;
  motionSend: string;
  motionReady: string;
  motionPause: string;
  motionResume: string;
};

export type LocalizedCopy = {
  heroTitle: [string, string];
  heroBody: string;
  startExperience: string;
  readDocs: string;
  installTitle: string;
  installBody: string;
  testkitInstallLink: string;
  installTabs: string;
  installPackage: string;
  installNote: string;
  installCandidateNote: string;
  copy: string;
  copied: string;
  copyError: string;
  capabilitiesTitle: string;
  capabilitiesBody: string;
  capabilities: Array<{ title: string; body: string; code: string }>;
  capabilityLedgerTitle: string;
  capabilityLedgerBody: string;
  capabilityReference: string;
  capabilityItemCount: string;
  capabilityGroups: Array<{
    id: CapabilityGroupId;
    code: string;
    title: string;
    summary: string;
    href: string;
    linkLabel: string;
    items: Array<{ signal: string; title: string; body: string }>;
  }>;
  workflowTitle: string;
  workflowBody: string;
  workflowAgent: string;
  workflowAgentBody: string;
  workflowAcl: string;
  workflowAclBody: string;
  workflowAgentLink: string;
  workflowAclLink: string;
  workflowObserve: string;
  workflowDecide: string;
  workflowAct: string;
  workflowProve: string;
  ctaTitle: string;
  ctaBody: string;
  quickStart: string;
  testkitGuide: string;
  footer: string;
  experience: ExperienceCopy;
};
