interface MarkdownNode {
  children?: MarkdownNode[];
  lang?: string | null;
  meta?: string | null;
  type?: string;
}

/**
 * Rspress does not bundle an ACL grammar. Render ACL as plain text while
 * preserving its language label. This is syntax presentation only; ACL is
 * parsed and generated by a3s-acl in product code.
 */
export function remarkAclSyntax() {
  return (tree: MarkdownNode) => {
    const visit = (node: MarkdownNode) => {
      if (node.type === 'code' && node.lang?.toLowerCase() === 'acl') {
        node.lang = 'text';
        node.meta = [node.meta, 'displayLanguage=ACL']
          .filter(Boolean)
          .join(' ');
      }
      node.children?.forEach(visit);
    };

    visit(tree);
  };
}
